export default {
  qualityIndicators: [],
  productTypes: {
    grain: [],
    product: [],
    periodProduct: [],
    periodGrain: [],
  },
  lotsTarget: [],
  lotsPurpose: [],
  transportTypes: [],
  sampleTypes: [],
  processingMethods: [],
  unitsOfMeasure: [],
  indicatorPurposes: [],
  okpd2List: [],
  okpd2MshList: {
    grain: [],
    product: [],
    periodProduct: [],
    periodGrain: [],
  },
  propertyRights: [],
  propertyRightTransferDocTypes: [],
  reasonWriteOffList: [],
  storageTypes: [],
  weightDisperancyCauses: [],
};
