export default {
  lot_list: {},
  lot_elevator_list: {},
  lots_gpb_list: {},
  sdiz_list: {},
  sdiz_elevator_list: {},
  sdiz_gpb_list: {},
  gosmonitoring_register_conducted_research_manufacturers: {},
  gosmonitoring_research_register: {},
  gosmonitoring_register_implementation: {},
  gosmonitoring_register_submitted_by_manufacturers: {},
  gpbo_gpb_out_list: {},
  rshn_expertise_list: {},
  rshn_prescription_list: {},
  rshn_withdrawal_list: {},
  sdiz_agent_list: {},
  ogv_list: {},
  ogv_list_elevator: {},
  ogv_list_gpb: {},
  ogv_agent_list_sdiz: {},
  ogv_sdizs_list: {},
  ogv_sdizs_list_gpb: {},
  ogv_list_gpb_out: {},
};
