<?php

namespace App\Repository\OAuth;

use App\Entity\OAuth\AccessToken;
use App\Entity\User\User;
use App\Repository\AutowiredRepositoryTrait;
use App\Traits\IsolatedEntityManagerTrait;

/**
 * AccessTokenRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessTokenRepository extends \Doctrine\ORM\EntityRepository
{
    public static string $entityClass = AccessToken::class;

    use IsolatedEntityManagerTrait;
    use AutowiredRepositoryTrait;

    /**
     * @param User $user
     */
    public function removeTokensByUser(User $user)
    {
        $tokens = $this->findBy(['user' => $user]);
        /** @var AccessToken $token */
        foreach ($tokens as $token) {
            $this->remove($token);
        }
    }
}
