<?php

namespace App\Repository\OAuth;

use App\Entity\OAuth\AuthCode;
use App\Repository\AutowiredRepositoryTrait;
use App\Traits\IsolatedEntityManagerTrait;

/**
 * AuthCodeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthCodeRepository extends \Doctrine\ORM\EntityRepository
{
    public static string $entityClass = AuthCode::class;

    use IsolatedEntityManagerTrait;
    use AutowiredRepositoryTrait;
}
