<?php

namespace App\Repository\OAuth;

use App\Entity\OAuth\Client;
use App\Repository\AutowiredRepositoryTrait;
use App\Traits\IsolatedEntityManagerTrait;

/**
 * ClientRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{
    public static string $entityClass = Client::class;

    use IsolatedEntityManagerTrait;
    use AutowiredRepositoryTrait;
}
