<?php

namespace App\Repository\OAuth;

use App\Entity\OAuth\RefreshToken;
use App\Entity\User\User;
use App\Repository\AutowiredRepositoryTrait;
use App\Traits\IsolatedEntityManagerTrait;
use Doctrine\ORM\EntityRepository;

/**
 * RefreshTokenRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefreshTokenRepository extends EntityRepository
{
    public static string $entityClass = RefreshToken::class;

    use IsolatedEntityManagerTrait;
    use AutowiredRepositoryTrait;

    /**
     * @param User $user
     */
    public function removeTokensByUser(User $user)
    {
        $tokens = $this->findBy(['user' => $user]);
        /** @var RefreshToken $token */
        foreach ($tokens as $token) {
            $this->remove($token);
        }
    }
}
