<?php

namespace App\Repository\Security;

use App\Entity\Security\Role;
use App\Repository\AutowiredRepositoryTrait;
use App\Traits\IsolatedEntityManagerTrait;

/**
 * RoleRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends \Doctrine\ORM\EntityRepository
{
    use IsolatedEntityManagerTrait;
    use AutowiredRepositoryTrait;

    protected static $entityClass = Role::class;
}
